add a modification on the test executor, now all tests are executed even if failure
git-svn-id: https://svn.cern.ch/reps/lcgutil/gfal/branches/gfal_2_0_dev@3136 4525493e-7705-40b1-a816-d608a930855b

diff --git a/testing/build/exec_tests b/testing/build/exec_tests
--- a/testing/build/exec_tests
+++ b/testing/build/exec_tests
@@ -19,6 +19,7 @@ if [ "$?" != "0" ]; then
 fi
 
 log=''
+resu=0
 dirn=`dirname $0`
 cd $dirn
 for f in `ls test_*.sh`
@@ -27,8 +28,7 @@ do
 	r=$?
 	if [[ "$r" != "0" ]]; then
 		pr=" $f .........error code: $r [FAIL]"
-		echo $pr
-		exit -1
+		resu=-1
 	else
 		pr=" $f .......... [OK]"
 	fi
@@ -36,4 +36,7 @@ do
 	log="$log\n$pr"
 done
 echo -e $log > testresult.txt
-
+if [[ "$resu" != "0"]]; then
+	echo "Failure of the tests !!" >&2
+	exit -1
+fi
