-All old functionals test migrated
git-svn-id: https://svn.cern.ch/reps/lcgutil/gfal/branches/gfal_2_0_dev@3087 4525493e-7705-40b1-a816-d608a930855b

diff --git a/testing/build/exec_tests b/testing/build/exec_tests
--- a/testing/build/exec_tests
+++ b/testing/build/exec_tests
@@ -5,8 +5,19 @@
 
 
 echo " ****************** script for functional Tests *******************"
-echo "WARNING: This tests need a voms proxy activated and a grid environnement"
+echo "WARNING: This tests need a voms proxy activated on dteam vo, a grid environnement"
 echo "Launch tests..... "
+which voms-proxy-info &> /dev/null
+if [ "$?" != "0" ]; then
+	echo " Error voms-proxy-info not found, grid env is not operational" >&2
+	exit -1
+fi
+voms-proxy-info &> /dev/null
+if [ "$?" != "0" ]; then
+	echo -e " Error : voms proxy not started, start it and retry \n\t\t example : voms-proxy-init --voms dteam" >&2
+	exit -1
+fi
+
 log=''
 dirn=`dirname $0`
 cd $dirn
